/* automatically generated by rust-bindgen */


#![allow(non_snake_case)]


#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct std_char_traits<_CharT> {
    pub _address: u8,
    pub _phantom_0: ::std::marker::PhantomData<_CharT>,
}
#[repr(C)]
#[derive(Debug, Copy)]
pub struct __gnu_cxx_char_traits {
    pub _address: u8,
}
impl Clone for __gnu_cxx_char_traits {
    fn clone(&self) -> Self { *self }
}
