/* automatically generated by rust-bindgen */


#![allow(non_snake_case)]


pub type foo =
    ::std::option::Option<unsafe extern "C" fn(bar: ::std::os::raw::c_int)
                              -> ::std::os::raw::c_int>;
