/* automatically generated by rust-bindgen */


#![allow(non_snake_case)]


pub mod root {
    #[allow(unused_imports)]
    use root;
    pub mod outer {
        #[allow(unused_imports)]
        use root;
        pub mod inner {
            #[allow(unused_imports)]
            use root;
            #[repr(C)]
            #[derive(Debug, Copy)]
            pub struct Helper {
                pub _address: u8,
            }
            #[test]
            fn bindgen_test_layout_Helper() {
                assert_eq!(::std::mem::size_of::<Helper>() , 1usize);
                assert_eq!(::std::mem::align_of::<Helper>() , 1usize);
            }
            impl Clone for Helper {
                fn clone(&self) -> Self { *self }
            }
        }
        #[repr(C)]
        #[derive(Debug, Copy)]
        pub struct Test {
            pub helper: root::outer::inner::Helper,
        }
        #[test]
        fn bindgen_test_layout_Test() {
            assert_eq!(::std::mem::size_of::<Test>() , 1usize);
            assert_eq!(::std::mem::align_of::<Test>() , 1usize);
        }
        impl Clone for Test {
            fn clone(&self) -> Self { *self }
        }
    }
}
