/* automatically generated by rust-bindgen */


#![allow(non_snake_case)]


#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Base<T> {
    pub _address: u8,
    pub _phantom_0: ::std::marker::PhantomData<T>,
}
#[repr(C)]
#[derive(Debug, Copy)]
pub struct Derived {
    pub _address: u8,
}
#[test]
fn bindgen_test_layout_Derived() {
    assert_eq!(::std::mem::size_of::<Derived>() , 1usize , concat ! (
               "Size of: " , stringify ! ( Derived ) ));
    assert_eq! (::std::mem::align_of::<Derived>() , 1usize , concat ! (
                "Alignment of " , stringify ! ( Derived ) ));
}
impl Clone for Derived {
    fn clone(&self) -> Self { *self }
}
#[repr(C)]
#[derive(Debug)]
pub struct BaseWithDestructor<T> {
    pub _address: u8,
    pub _phantom_0: ::std::marker::PhantomData<T>,
}
#[repr(C)]
#[derive(Debug)]
pub struct DerivedFromBaseWithDestructor {
    pub _address: u8,
}
#[test]
fn bindgen_test_layout_DerivedFromBaseWithDestructor() {
    assert_eq!(::std::mem::size_of::<DerivedFromBaseWithDestructor>() , 1usize
               , concat ! (
               "Size of: " , stringify ! ( DerivedFromBaseWithDestructor ) ));
    assert_eq! (::std::mem::align_of::<DerivedFromBaseWithDestructor>() ,
                1usize , concat ! (
                "Alignment of " , stringify ! ( DerivedFromBaseWithDestructor
                ) ));
}
#[test]
fn __bindgen_test_layout_template_1() {
    assert_eq!(::std::mem::size_of::<Base<Derived>>() , 1usize , concat ! (
               "Size of template specialization: " , stringify ! (
               Base<Derived> ) ));
    assert_eq!(::std::mem::align_of::<Base<Derived>>() , 1usize , concat ! (
               "Alignment of template specialization: " , stringify ! (
               Base<Derived> ) ));
}
#[test]
fn __bindgen_test_layout_template_2() {
    assert_eq!(::std::mem::size_of::<BaseWithDestructor<DerivedFromBaseWithDestructor>>()
               , 1usize , concat ! (
               "Size of template specialization: " , stringify ! (
               BaseWithDestructor<DerivedFromBaseWithDestructor> ) ));
    assert_eq!(::std::mem::align_of::<BaseWithDestructor<DerivedFromBaseWithDestructor>>()
               , 1usize , concat ! (
               "Alignment of template specialization: " , stringify ! (
               BaseWithDestructor<DerivedFromBaseWithDestructor> ) ));
}
