/* automatically generated by rust-bindgen */

#![allow(
    dead_code,
    non_snake_case,
    non_camel_case_types,
    non_upper_case_globals
)]

pub type EmptyConstified = u32;
#[repr(u32)]
#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash)]
pub enum EmptyRustified {
    __bindgen_cannot_repr_c_on_empty_enum = 0,
}
pub mod EmptyModule {
    pub type Type = u32;
}
#[repr(i8)]
#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash)]
pub enum EmptyClassRustified {
    __bindgen_cannot_repr_c_on_empty_enum = 0,
}
pub type EmptyClassConstified = i8;
pub mod EmptyClassModule {
    pub type Type = i8;
}
#[repr(i8)]
#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash)]
pub enum ForwardClassRustified {
    __bindgen_cannot_repr_c_on_empty_enum = 0,
}
pub type ForwardClassConstified = i8;
pub mod ForwardClassModule {
    pub type Type = i8;
}
