/* automatically generated by rust-bindgen */


#![allow(non_snake_case)]


pub type __void_t = ::std::os::raw::c_void;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __iterator_traits<_Iterator> {
    pub _address: u8,
    pub _phantom_0: ::std::marker::PhantomData<_Iterator>,
}
impl <_Iterator> Default for __iterator_traits<_Iterator> {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
