/* automatically generated by rust-bindgen */


#![allow(non_snake_case)]


pub type __void_t = ::std::os::raw::c_void;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct __iterator_traits {
    pub _address: u8,
}
