/* automatically generated by rust-bindgen */

#![allow(dead_code, non_snake_case, non_camel_case_types, non_upper_case_globals)]

#[doc = " <div rustbindgen replaces=\"PASS\"></div>\n\n Should see PASS below."]
pub const OGRErr_PASS: OGRErr = 0;
#[doc = " <div rustbindgen replaces=\"OGRERR_NONE\"></div>\n\n Should see OGRERR_NONE instead of CUSTOM_OGRERR_NONE below."]
pub const OGRErr_OGRERR_NONE: OGRErr = 1;
#[doc = " <div rustbindgen replaces=\"OGRErr\"></div>"]
pub type OGRErr = u32;
