/* automatically generated by rust-bindgen */


#![allow(dead_code, non_snake_case, non_camel_case_types, non_upper_case_globals)]


pub const g_107: ::std::os::raw::c_ulonglong = 18446744073709551615;
