/* automatically generated by rust-bindgen */


#![allow(non_snake_case)]


/** <div rustbindgen nocopy></div> */
#[repr(C)]
#[derive(Debug, Default)]
pub struct CopiableButWait {
    pub whatever: ::std::os::raw::c_int,
}
