/* automatically generated by rust-bindgen */


#![allow(non_snake_case)]

#![cfg(target_os="macos")]

#[macro_use]
extern crate objc;
#[allow(non_camel_case_types)]
pub type id = *mut objc::runtime::Object;
pub trait Foo {
    unsafe fn method(self);
}
impl Foo for id {
    unsafe fn method(self) { msg_send!(self , method) }
}
pub trait Foo_BarCategory {
    unsafe fn categoryMethod(self);
}
impl Foo_BarCategory for id {
    unsafe fn categoryMethod(self) { msg_send!(self , categoryMethod) }
}
