/* automatically generated by rust-bindgen */


#![allow(non_snake_case)]


#[repr(C)]
#[derive(Debug, Copy)]
pub struct C {
    pub arr: [u32; 3usize],
}
#[test]
fn bindgen_test_layout_C() {
    assert_eq!(::std::mem::size_of::<C>() , 12usize);
    assert_eq! (::std::mem::align_of::<C>() , 4usize);
    assert_eq! (unsafe {
                & ( * ( 0 as * const C ) ) . arr as * const _ as usize } ,
                0usize);
}
impl Clone for C {
    fn clone(&self) -> Self { *self }
}
