/* automatically generated by rust-bindgen */

pub use self::root::*;

#[allow(non_snake_case, non_camel_case_types, non_upper_case_globals)]
pub mod root {
    #[allow(unused_imports)]
    use self::super::*;
    #[repr(C)]
    #[derive(Default)]
    pub struct C__bindgen_vtable {
    }
    #[repr(C)]
    #[derive(Debug, Copy)]
    pub struct C {
        pub vtable_: *const C__bindgen_vtable,
    }
    #[test]
    fn bindgen_test_layout_C() {
        assert_eq!(::std::mem::size_of::<C>() , 8usize , concat ! (
                   "Size of: " , stringify ! ( C ) ));
        assert_eq! (::std::mem::align_of::<C>() , 8usize , concat ! (
                    "Alignment of " , stringify ! ( C ) ));
    }
    impl Clone for C {
        fn clone(&self) -> Self { *self }
    }
    impl Default for C {
        fn default() -> Self { unsafe { ::std::mem::zeroed() } }
    }
}
