/* automatically generated by rust-bindgen */

pub use self::root::*;

#[allow(non_snake_case, non_camel_case_types, non_upper_case_globals)]
pub mod root {
    #[allow(unused_imports)]
    use self::super::*;
    #[repr(C)]
    #[derive(Debug, Copy, Clone)]
    pub struct WhitelistMe<T> {
        pub foo: ::std::os::raw::c_int,
        pub bar: WhitelistMe_Inner<T>,
    }
    #[repr(C)]
    #[derive(Debug, Copy, Clone)]
    pub struct WhitelistMe_Inner<T> {
        pub bar: T,
    }
    impl <T> Default for WhitelistMe_Inner<T> {
        fn default() -> Self { unsafe { ::std::mem::zeroed() } }
    }
    impl <T> Default for WhitelistMe<T> {
        fn default() -> Self { unsafe { ::std::mem::zeroed() } }
    }
}
