/* automatically generated by rust-bindgen */


#![allow(dead_code, non_snake_case, non_camel_case_types, non_upper_case_globals)]


pub const NONE: ::std::os::raw::c_uint = 0;
pub const FOO: ::std::os::raw::c_uint = 5;
pub const FOOB: ::std::os::raw::c_int = -2;
pub const FOOBAR: ::std::os::raw::c_int = -10;
