/* automatically generated by rust-bindgen */


#![allow(non_snake_case)]


pub type whatever_t = ::std::os::raw::c_int;
extern "C" {
    #[link_name = "_Z9somethingPKi"]
    pub fn something(wat: *const whatever_t);
}
