/* automatically generated by rust-bindgen */


#![feature(const_fn)]
#![allow(non_snake_case)]


#[repr(u32)]
#[derive(Debug, Copy, Clone)]
pub enum Enum_Foo { Bar = 0, Qux = 1, }
#[repr(i32)]
#[derive(Debug, Copy, Clone)]
pub enum Enum_Neg { MinusOne = -1, One = 1, }
