[package]
name = "tests_expectations"
description = "bindgen results when ran on ../headers/*"
version = "0.0.0"
authors = [
  "Jyun-Yan You <jyyou.tw@gmail.com>",
  "Emilio Cobos Álvarez <emilio@crisal.io>",
  "The Servo project developers",
]
publish = false
rust-version.workspace = true
edition.workspace = true

[dependencies]
block.workspace = true
libloading.workspace = true
objc.workspace = true

# Both of these sections need to be copied here from the workspace because
# Cargo currently does not allow overriding workspace settings in a member
[lints.rust]
### FIXME: these might need to be fixed,
###   esp the calling convention, because it is a hard error now
# deprecated = "allow"
# invalid_value = "allow"
# unsupported_calling_conventions = "allow"
#
# Different from the workspace
dead_code = "allow"
non_snake_case = "allow"
non_camel_case_types = "allow"
non_upper_case_globals = "allow"
unexpected_cfgs = "allow"
unused_qualifications = "allow"

[lints.clippy]
disallowed_names = "allow"
manual_c_str_literals = "allow"
missing_safety_doc = "allow"
op_ref = "allow"
ptr_offset_with_cast = "allow"
semicolon_if_nothing_returned = "allow"
too_many_arguments = "allow"
transmute_int_to_bool = "allow"
unnecessary_cast = "allow"
useless_transmute  = "allow"
