name: all-rust-targets

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-expectations:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        # TODO(#1954): These should be run on mac too, but turns out they're
        # broken.
        os: [ubuntu-latest, macos-latest]
        rust: ["1.0.0", "1.17.0", "1.19.0", "1.20.0", "1.21.0", "1.25.0", "1.26.0", "1.27.0", "1.28.0", "1.30.0", "1.33.0", "1.36.0", "1.40.0", "1.47.0", "1.64.0", nightly]
    steps:
      - uses: actions/checkout@v3

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{matrix.rust}}
          override: true

      - name: Test expectations
        run: cd bindgen-tests/tests/expectations && cargo test
        env:
          RUSTFLAGS: "-D unsafe_op_in_unsafe_fn -D unused_unsafe"
